services:
  wakewise_postgres:
    build:
      context: .
      args:
        DEV_SCRIPTS: "false"
    container_name: wakewise_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wakewise
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wakewise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: