-- Mock data generated by ChatGPT

/* ---------- users ------------------------------------------------------ */
INSERT INTO users (
        username,
        password_hash,
        is_admin,
        created_at
    )
VALUES (
        'J. Junior',
        '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
        FALSE,
        '2025-04-21 18:00:00+02'
    ),
    (
        'Jonathan',
        '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
        TRUE,
        '2025-04-21 18:05:00+02'
    );
/* ---------- sleep_history (only regular user) ------------------------- */
INSERT INTO sleep_history (
        planned_start,
        planned_end,
        actual_start,
        actual_end,
        recordings_enabled,
        ambient_noise_enabled,
        score,
        time_in_bed,
        total_phone_use,
        user_note
    )
VALUES (
        '2025-04-22 23:00:00+02',
        '2025-04-23 07:00:00+02',
        '2025-04-22 23:10:00+02',
        '2025-04-23 07:10:00+02',
        TRUE,
        TRUE,
        88,
        465,
        12,
        'Felt refreshed.'
    );
/* ---------- phone_occupancy (user id ⇒ sleep_id = 1) ------------------ */
INSERT INTO phone_occupancy (sleep_id, start_timestamp, duration)
VALUES (1, '2025-04-22 23:15:00+02', 5 * 3600),
    (1, '2025-04-23 04:20:00+02', 3 * 3600);
/* ---------- bed_occupancy --------------------------------------------- */
INSERT INTO bed_occupancy (sleep_id, start_timestamp, duration)
VALUES (1, '2025-04-22 23:10:00+02', 8 * 3600);
-- single 8 h interval
/* ---------- environment_history (hourly samples) ---------------------- */
INSERT INTO environment_history (
        sleep_id,
        stored_on,
        room_temperature,
        room_humidity
    )
VALUES (1, '2025-04-23 00:00:00+02', 21.5, 45),
    (1, '2025-04-23 02:00:00+02', 21.2, 46),
    (1, '2025-04-23 04:00:00+02', 21.0, 47),
    (1, '2025-04-23 06:00:00+02', 20.8, 48);
/* ---------- files_metadata + recordings ------------------------------- */
INSERT INTO files_metadata (
        file_name,
        mime_type,
        size_bytes,
        created_at,
        updated_at
    )
VALUES (
        'jonathan_2025-04-23_01-15.wav',
        'audio/wav',
        2_100_000,
        '2025-04-23 07:05:00+02',
        '2025-04-23 07:05:00+02'
    ),
    (
        'flora_2025-04-25_01-15.wav',
        'audio/wav',
        4_200_000,
        '2025-04-25 05:38:00+02',
        '2025-04-25 05:38:00+02'
    ),
    ( 'flora_2025-04-28_01-15.wav',
        'audio/wav',
        1_200_000,
        '2025-04-28 06:10:00+02',
        '2025-04-28 06:10:00+02'
        ),
    ( 'flora_2025-04-29_01-15.wav',
        'audio/wav',
        1_200_000,
        '2025-04-28 06:10:00+02',
        '2025-04-28 06:10:00+02');
INSERT INTO recordings (
        file_id,
        sleep_id,
        start_time,
        duration_seconds,
        peak_volume,
        is_favorite,
        user_note
    )
VALUES (
        1,
        1,
        '2025-04-23 01:15:12+02',
        12,
        -20,
        TRUE,
        'Funny sleep-talk segment'
    );