-- Mock data generated by ChatGPT

/* ---------- users ------------------------------------------------------ */
INSERT INTO
    users (
        username,
        password_hash,
        is_admin,
        created_at
    )
VALUES (
        'J. Junior',
        '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
        FALSE,
        '2025-04-21 18:00:00+02'
    ),
    (
        'Jonathan',
        '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
        TRUE,
        '2025-04-21 18:05:00+02'
    );
/* ---------- sleep_history (only regular user) ------------------------- */
INSERT INTO
    sleep_history (
        planned_start,
        planned_end,
        actual_start,
        actual_end,
        recordings_enabled,
        ambient_noise_enabled,
        score,
        time_in_bed,
        total_phone_use,
        user_note
    )
VALUES (
        '2025-04-22 23:00:00+02',
        '2025-04-23 07:00:00+02',
        '2025-04-22 23:10:00+02',
        '2025-04-23 07:10:00+02',
        TRUE,
        TRUE,
        88,
        465,
        12,
        'Felt refreshed.'
    );
/* ---------- phone_occupancy (user id ⇒ sleep_id = 1) ------------------ */
INSERT INTO
    phone_occupancy (
        sleep_id,
        start_timestamp,
        duration
    )
VALUES (
        1,
        '2025-04-22 23:15:00+02',
        5 * 3600
    ),
    (
        1,
        '2025-04-23 04:20:00+02',
        3 * 3600
    );
/* ---------- bed_occupancy --------------------------------------------- */
INSERT INTO
    bed_occupancy (
        sleep_id,
        start_timestamp,
        duration
    )
VALUES (
        1,
        '2025-04-22 23:10:00+02',
        8 * 3600
    );
-- single 8 h interval
/* ---------- environment_history (hourly samples) ---------------------- */
INSERT INTO
    environment_history (
        sleep_id,
        stored_on,
        room_temperature,
        room_humidity
    )
VALUES (
        1,
        '2025-04-23 00:00:00+02',
        21.5,
        45
    ),
    (
        1,
        '2025-04-23 02:00:00+02',
        21.2,
        46
    ),
    (
        1,
        '2025-04-23 04:00:00+02',
        21.0,
        47
    ),
    (
        1,
        '2025-04-23 06:00:00+02',
        20.8,
        48
    );
/* ---------- files_metadata + recordings ------------------------------- */
INSERT INTO files_metadata (
        file_name,
        mime_type,
        size_bytes,
        created_at,
        updated_at
    )
VALUES (
        'Kista.mp3',
        'application/octet-stream',
        51661,
        '2025-05-09 11:32:54.11403+00',
        '2025-05-09 11:32:54.11403+00'
    );

INSERT INTO
    recordings (
        file_id,
        sleep_id,
        start_time,
        duration_seconds,
        peak_volume,
        is_favorite,
        user_note
    )
VALUES (
        6,
        1,
        '2025-05-09 11:32:54.11403+00',
        6,
        -20,
        False,
        'Funny sleep-talk segment'
    ),
    (
        3,
        1,
        '2025-05-09 11:32:54.11403+00',
        6,
        -20,
        False,
        'Funny sleep-talk segment'
    );
   

    INSERT INTO lights (
        color_hex,
        color_rgb
    )
    VALUES(
        
        '#FFFFFF',
        '208, 2, 27'
    ),
    (
        
        '#FFFFFF',
        '208, 2, 27'
    ),
    (
        
        '#FFFFFF',
        '208, 2, 27'
    ),
    (
        
        '#FFFFFF',
        '208, 2, 27'
    )