-- SQLBook: Code
-- Mock data generated by ChatGPT

/* ---------- users ------------------------------------------------------ */
-- INSERT INTO
--     users (
--         username,
--         password_hash,
--         is_admin,
--         created_at
--     )
-- VALUES (
--         'J. Junior',
--         '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
--         FALSE,
--         '2025-04-21 18:00:00+02'
--     ),
--     (
--         'Jonathan',
--         '$2b$10$OLZ7HzwbhGgUnZn1SNWMc.2FOkSsShxZnkpZSXAMlAjrRxc0jVQ4G',
--         TRUE,
--         '2025-04-21 18:05:00+02'
--     );
/* ---------- sleep_history (only regular user) ------------------------- */
INSERT INTO
    sleep_history (
        planned_start,
        planned_end,
        actual_start,
        actual_end,
        recordings_enabled,
        ambient_noise_enabled,
        score,
        time_in_bed,
        total_phone_use,
        user_note
    )
VALUES (
        '2025-04-22 23:00:00+02',
        '2025-04-23 07:00:00+02',
        '2025-04-22 23:10:00+02',
        '2025-04-23 07:10:00+02',
        TRUE,
        TRUE,
        30,
        465,
        20,
        'Felt refreshed.'
    ),
    (
    '2025-05-06 22:00:00+00',
    '2025-05-07 06:00:00+00',
    '2025-05-06 22:10:00+00',
    '2025-05-07 06:05:00+00',
    TRUE,
    TRUE,
    85,
    475,
    10,
    'Felt rested, solid night.'
),
(
    '2025-05-07 22:30:00+00',
    '2025-05-08 06:30:00+00',
    '2025-05-07 22:40:00+00',
    '2025-05-08 06:25:00+00',
    FALSE,
    TRUE,
    75,
    465,
    12,
    'Took a while to fall asleep, but stayed asleep.'
),
(
    '2025-05-08 23:00:00+00',
    '2025-05-09 07:00:00+00',
    '2025-05-08 23:05:00+00',
    '2025-05-09 06:50:00+00',
    TRUE,
    FALSE,
    90,
    470,
    15,
    'Woke up early, but sleep was deep.'
),
(
    '2025-05-09 21:45:00+00',
    '2025-05-10 05:45:00+00',
    '2025-05-09 21:50:00+00',
    '2025-05-10 05:30:00+00',
    FALSE,
    FALSE,
    65,
    440,
    8,
    'Kept waking up.'
),
(
    '2025-05-10 23:15:00+00',
    '2025-05-11 07:15:00+00',
    '2025-05-10 23:25:00+00',
    '2025-05-11 07:10:00+00',
    TRUE,
    TRUE,
    88,
    485,
    30,
    'Slept very well.'
),
(
    '2025-05-11 22:00:00+00',
    '2025-05-12 06:00:00+00',
    '2025-05-11 22:20:00+00',
    '2025-05-12 06:00:00+00',
    FALSE,
    TRUE,
    72,
    460,
    30,
    'Had trouble sleeping early on.'
),
(
    '2025-05-12 22:45:00+00',
    '2025-05-13 06:45:00+00',
    '2025-05-12 22:50:00+00',
    '2025-05-13 06:50:00+00',
    TRUE,
    TRUE,
    91,
    480,
    25,
    'Very refreshing sleep.'
),
(
    '2025-05-13 23:30:00+00',
    '2025-05-14 07:30:00+00',
    '2025-05-13 23:35:00+00',
    '2025-05-14 07:20:00+00',
    TRUE,
    FALSE,
    78,
    470,
    30,
    'Late start, but decent quality.'
),
(
    '2025-05-14 21:30:00+00',
    '2025-05-15 05:30:00+00',
    '2025-05-14 23:50:00+00',
    '2025-05-15 06:10:00+00',
    TRUE,
    TRUE,
    87,
    480,
    5,
    'Dreamed of '
),
(
    '2025-05-15 22:10:00+00',
    '2025-05-16 06:10:00+00',
    '2025-05-15 22:25:00+00',
    '2025-05-16 06:00:00+00',
    FALSE,
    FALSE,
    68,
    455,
    15,
    'Today I dreamt of unicorns and cotton candy'
);



    /* ---------- phone_occupancy (user id ⇒ sleep_id = 1) ------------------ */
INSERT INTO
    phone_occupancy (
        sleep_id,
        start_timestamp,
        duration
    )
VALUES (
        1,
        '2025-04-22 23:15:00+02',
        5 * 3600
    ),
    (
        1,
        '2025-04-23 04:20:00+02',
        3 * 3600
    );
/* ---------- bed_occupancy --------------------------------------------- */
INSERT INTO
    bed_occupancy (
        sleep_id,
        start_timestamp,
        duration
    )
VALUES (
        1,
        '2025-04-22 23:10:00+02',
        8 * 3600
    );
-- single 8 h interval
/* ---------- environment_history (hourly samples) ---------------------- */
INSERT INTO
    environment_history (
        sleep_id,
        stored_on,
        room_temperature,
        room_humidity
    )
VALUES (
    1,
    '2025-05-06 06:00:00+00',
    21.5,
    44
),
(   1,
    '2025-05-06 04:00:00+00',
    22,
    44
),
(   1,
    '2025-05-06 02:00:00+00',
    21.3,
    44
),
(
    2,
    '2025-05-07 06:00:00+00',
    21.3,
    45
),
(
    3,
    '2025-05-08 06:00:00+00',
    21.1,
    46
),
(
    4,
    '2025-05-09 06:00:00+00',
    20.9,
    47
),
(
    5,
    '2025-05-10 06:00:00+00',
    20.7,
    48
),
(
    6,
    '2025-05-11 06:00:00+00',
    21.0,
    46
),
(
    7,
    '2025-05-12 06:00:00+00',
    21.2,
    45
),
(
    8,
    '2025-05-13 06:00:00+00',
    21.4,
    44
),
(
    9,
    '2025-05-14 06:00:00+00',
    21.1,
    46
),
(
    9,
    '2025-05-14 04:00:00+00',
    20,
    46
),
(
    9,
    '2025-05-14 03:00:00+00',
    22,
    46
),
(
    10,
    '2025-05-15 06:00:00+00',
    20.8,
    47
),
(
    11,
    '2025-05-16 06:00:00+00',
    20.3,
    48
),
(
    11,
    '2025-05-16 04:00:00+00',
    21.6,
    48
),
(
    11,
    '2025-05-16 03:00:00+00',
    22.6,
    48
),
(
    11,
    '2025-05-16 05:00:00+00',
    21.5,
    48
);

/* ---------- files_metadata + recordings ------------------------------- */
-- INSERT INTO files_metadata (
--         file_name,
--         mime_type,
--         size_bytes,
--         created_at,
--         updated_at
--     )
-- VALUES (
--         'jonathan_2025-04-23_01-15.wav',
--         'audio/wav',
--         2_100_000,
--         '2025-04-23 07:05:00+02',
--         '2025-04-23 07:05:00+02'
--     );

-- INSERT INTO
--     recordings (
--         file_id,
--         sleep_id,
--         start_time,
--         duration_seconds,
--         peak_volume,
--         is_favorite,
--         user_note
--     )
-- VALUES (
--         6,
--         1,
--         '2025-04-23 01:15:12+02',
--         12,
--         -20,
--         TRUE,
--         'Funny sleep-talk segment'
--     );